In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("homeprices.csv")
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [3]:
dummies = pd.get_dummies(df.town)
dummies

    monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [4]:
pd.concat([df, dummies],axis='columns')

               town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [5]:
df_dummies = pd.concat([df, dummies],axis='columns')
df_dummies

               town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [6]:
df_dummies.drop(['town','west windsor'],axis='columns' , inplace=True)
df_dummies # 2 coulmns dropped due to dummy variable trap to find the derivation between two 2 columns (monroe township,robinsville) and maintain the collinearity between 2

    area   price  monroe township  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

In [7]:
X = df_dummies.drop('price',axis='columns')
X

    area  monroe township  robinsville
0   2600                1            0
1   3000                1            0
2   3200                1            0
3   3600                1            0
4   4000                1            0
5   2600                0            0
6   2800                0            0
7   3300                0            0
8   3600                0            0
9   2600                0            1
10  2900                0            1
11  3100                0            1
12  3600                0            1

In [8]:
y = df_dummies.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [9]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X,y)

LinearRegression()

In [10]:
model.predict([[3400,0,0]])

C:\Users\ayush\miniconda3\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([681241.66845839])

In [11]:
model.predict([[2800,0,1]])

C:\Users\ayush\miniconda3\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([590775.63964739])

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder() # one hot label encoder

In [13]:
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [14]:
dfle = df
dfle.town = le.fit_transform(dfle.town)
dfle  #Label encorder assigns the town strings to random int

    town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [15]:
X = dfle[['town','area']]
X #price dropped cloumn

    town  area
0      0  2600
1      0  3000
2      0  3200
3      0  3600
4      0  4000
5      2  2600
6      2  2800
7      2  3300
8      2  3600
9      1  2600
10     1  2900
11     1  3100
12     1  3600

In [27]:
X = dfle[['town','area']].values
X #convert it to 2D array using .values

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]], dtype=int64)

In [28]:
y = dfle.price.values
y # convert prices into 1D array

array([550000, 565000, 610000, 680000, 725000, 585000, 615000, 650000,
       710000, 575000, 600000, 620000, 695000], dtype=int64)

In [29]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\ayush\miniconda3\lib\site-packages (1.5.0)
Requirement already satisfied: numpy>=1.19.5 in c:\users\ayush\miniconda3\lib\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in c:\users\ayush\miniconda3\lib\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\ayush\miniconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\ayush\miniconda3\lib\site-packages (from scikit-learn) (3.5.0)

[notice] A new release of pip is available: 24.0 -> 24.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [31]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('town', OneHotEncoder(), [0])], remainder = 'passthrough')

In [32]:
X = ct.fit_transform(X)
X

array([[1.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.0e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.2e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.9e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.1e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.6e+03]])

In [33]:
X = X[:,1:]
X

array([[0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 3.6e+03]])

In [34]:
model.fit(X,y)

LinearRegression()

In [35]:
model.predict([[0,1,3400]])

array([681241.6684584])

In [40]:
import joblib

In [41]:
joblib.dump(model,'model_joblib')

['model_joblib']

In [42]:
ohe = joblib.load('model_joblib')

In [43]:
ohe.coef_

array([25686.4115244 , 40013.97548914,   126.89744141])

In [44]:
ohe.intercept_

209776.39217373997

In [47]:
ohe.predict([[0,1,3400]])

array([681241.6684584])

In [52]:
df = pd.read_csv("carprices.csv")
df

                 CarModel  Mileage  SellPrice  Age
0                  BMW X5    69000      18000    6
1                  BMW X5    35000      34000    3
2                  BMW X5    57000      26100    5
3                  BMW X5    22500      40000    2
4                  BMW X5    46000      31500    4
5                 Audi A5    59000      29400    5
6                 Audi A5    52000      32000    5
7                 Audi A5    72000      19300    6
8                 Audi A5    91000      12000    8
9   Mercedez Benz C class    67000      22000    6
10  Mercedez Benz C class    83000      20000    7
11  Mercedez Benz C class    79000      21000    7
12  Mercedez Benz C class    59000      33000    5

In [53]:
dummies = pd.get_dummies(df.CarModel)
dummies

    Audi A5  BMW X5  Mercedez Benz C class
0         0       1                      0
1         0       1                      0
2         0       1                      0
3         0       1                      0
4         0       1                      0
5         1       0                      0
6         1       0                      0
7         1       0                      0
8         1       0                      0
9         0       0                      1
10        0       0                      1
11        0       0                      1
12        0       0                      1

In [54]:
merged = pd.concat([df,dummies],axis='columns')
merged

,CarModel,Mileage,SellPrice,Age,Audi A5,BMW X5,Mercedez Benz C class
0,BMW X5,69000,18000,6,0,1,0
1,BMW X5,35000,34000,3,0,1,0
2,BMW X5,57000,26100,5,0,1,0
3,BMW X5,22500,40000,2,0,1,0
4,BMW X5,46000,31500,4,0,1,0
5,Audi A5,59000,29400,5,1,0,0
6,Audi A5,52000,32000,5,1,0,0
7,Audi A5,72000,19300,6,1,0,0
8,Audi A5,91000,12000,8,1,0,0
9,Mercedez Benz C class,67000,22000,6,0,0,1
10,Mercedez Benz C class,83000,20000,7,0,0,1
11,Mercedez Benz C class,79000,21000,7,0,0,1
12,Mercedez Benz C class,59000,33000,5,0,0,1

In [55]:
final = merged.drop(['CarModel'], axis='columns')
final

    Mileage  SellPrice  Age  Audi A5  BMW X5  Mercedez Benz C class
0     69000      18000    6        0       1                      0
1     35000      34000    3        0       1                      0
2     57000      26100    5        0       1                      0
3     22500      40000    2        0       1                      0
4     46000      31500    4        0       1                      0
5     59000      29400    5        1       0                      0
6     52000      32000    5        1       0                      0
7     72000      19300    6        1       0                      0
8     91000      12000    8        1       0                      0
9     67000      22000    6        0       0                      1
10    83000      20000    7        0       0                      1
11    79000      21000    7        0       0                      1
12    59000      33000    5        0       0                      1

In [56]:
final = final.drop(['Mercedez Benz C class'], axis='columns')
final

    Mileage  SellPrice  Age  Audi A5  BMW X5
0     69000      18000    6        0       1
1     35000      34000    3        0       1
2     57000      26100    5        0       1
3     22500      40000    2        0       1
4     46000      31500    4        0       1
5     59000      29400    5        1       0
6     52000      32000    5        1       0
7     72000      19300    6        1       0
8     91000      12000    8        1       0
9     67000      22000    6        0       0
10    83000      20000    7        0       0
11    79000      21000    7        0       0
12    59000      33000    5        0       0

In [57]:
X = final.drop('SellPrice', axis='columns')
X

    Mileage  Age  Audi A5  BMW X5
0     69000    6        0       1
1     35000    3        0       1
2     57000    5        0       1
3     22500    2        0       1
4     46000    4        0       1
5     59000    5        1       0
6     52000    5        1       0
7     72000    6        1       0
8     91000    8        1       0
9     67000    6        0       0
10    83000    7        0       0
11    79000    7        0       0
12    59000    5        0       0

In [60]:
y = final.SellPrice
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: SellPrice, dtype: int64

In [61]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [62]:
model.fit(X,y)

LinearRegression()

In [63]:
model.predict(X)

array([18705.2723644 , 35286.78445645, 24479.19112468, 41245.76426391,
       29882.98779056, 28023.6135243 , 30614.46818502, 21879.57266964,
       12182.34562104, 26183.72387884, 18929.31674102, 20409.80511857,
       30477.15426156])

In [64]:
model.score(X,y)

0.9417050937281082

In [65]:
model.predict([[45000,4,0,0]])

C:\Users\ayush\miniconda3\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([36991.31721061])

array([1.15625835e+09])